#!/usr/bin/env ruby
# frozen_string_literal: true

$stdout.sync = true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "nbf_tools"

puts NbfTools.operate_with_options(NbfTools::Options.new(ARGV).parse)
